/**
 * wrapper.js - Max-side glue for the Strudel devices (NOT the React app).
 * Shared by all three device variants (midi/sampler/audio), mode-switched by
 * jsarguments[0].
 *
 * 1. Load strudel-ui.html into [jweb] via a file:// URL from this patch path.
 * 2. write_clip: create a MIDI clip on THIS device's own track and fill it.
 * 3. read_notes: read the notes of the track's clip and send them to the UI.
 * 4. Extract the embedded node.script bundle to disk if frozen resolution fails.
 * 5. sampler mode: observe Live 12's global root_note/scale_name and forward
 *    them to the UI and to [node.script].
 *
 * Outlets:
 * 0 - to jweb ("url ...", "mode ...", "notes <loopEnd> <n> <p s d> ...")
 * 1 - to [node.script] (code/hush forwarded from jweb pass through directly;
 *     this outlet carries js-originated messages like "scale ...")
 */

autowatch = 1;
inlets = 1;
outlets = 2;

post("wrapper.js loaded (build " + (typeof BUILD_STAMP !== "undefined" ? BUILD_STAMP : "dev - no stamp") + ")\n");

var MODE = jsarguments.length > 0 ? String(jsarguments[0]) : "midi";

// Clip availability: polled (LiveAPI has no single observable for "any clip
// on this track"), pushed to the UI as `clip_available 0/1` on change so the
// From Clip button can disable itself when there is nothing to read.
var lastClipAvail = -1;
var clipPoll = new Task(checkClipAvailable, this);

// live.thisdevice fires bang() when the device is fully loaded in Live;
// loadbang() is unreliable inside M4L (observed not firing in Live 12), so
// the node bootstrap runs from BOTH and guards against double execution.
function bang() {
	post("strudel: bang (device ready)\n");
	extractNodeBundle();
	loadWebview();
	startClipPoll();
	setupScaleObservers();
	setupTempoObserver();
}
function loadbang() {
	post("strudel: loadbang\n");
	extractNodeBundle();
	loadWebview();
	setupScaleObservers();
	setupTempoObserver();
}
function reload() {
	extractNodeBundle();
	loadWebview();
	startClipPoll();
	setupScaleObservers();
	setupTempoObserver();
}

// Live's tempo in BPM, observed via LiveAPI and pushed to the UI (and to
// node in sampler mode). plugsync~ cannot provide this - its tempo outlet
// reports samples-per-beat. The observer callback also fires once with the
// current value when the property is attached.
var tempoObs = null;
function setupTempoObserver() {
	if (tempoObs) return;
	try {
		tempoObs = new LiveAPI(onTempo, "live_set");
		tempoObs.property = "tempo";
	} catch (e) {
		post("strudel: tempo observer unavailable - " + e.message + "\n");
	}
}
function onTempo(a) {
	if (a && a[0] == "tempo") {
		post("strudel: tempo " + a[1] + "\n");
		outlet(0, "tempo", a[1]); // → jweb (engine worker)
		if (MODE === "sampler") outlet(1, "tempo", a[1]); // → node (preview timing)
	}
}

function startClipPoll() {
	lastClipAvail = -1;
	clipPoll.cancel();
	clipPoll.interval = 1000;
	clipPoll.repeat();
}

function checkClipAvailable() {
	var avail = 0;
	try {
		avail = pickClip() ? 1 : 0;
	} catch (e) {
		avail = 0;
	}
	if (avail !== lastClipAvail) {
		lastClipAvail = avail;
		outlet(0, "clip_available", avail);
	}
}

/**
 * jweb's outlet fans out to BOTH this [js] and [node.script]; messages meant
 * for node (code/hush/preview/load_map/download/...) land here too. Swallow
 * them silently instead of logging "js: no function <name>" on every one.
 */
function anything() {}

/** UI announces it finished loading - resend current state. */
function ui_ready() {
	outlet(0, "mode", MODE);
	// The UI shows this next to its own baked-in version: a mismatch means a
	// mixed install (stale .amxd instance vs newer extracted UI, or vice versa).
	outlet(0, "build", buildStamp());
	sendCurrentTempo();
	lastClipAvail = -1;
	// midi + audio devices keep the To Clip/From Clip feature; sampler (an
	// audio-effect device with no MIDI notes of its own) does not.
	if (MODE !== "sampler") checkClipAvailable();
}

/** The observer's initial callback can fire before the page is bound - the
 *  ui_ready handshake re-reads the current tempo so the UI never misses it. */
function sendCurrentTempo() {
	try {
		var api = new LiveAPI(null, "live_set");
		var t = parseFloat(api.get("tempo"));
		if (t > 0) {
			outlet(0, "tempo", t);
			if (MODE === "sampler") outlet(1, "tempo", t);
		}
	} catch (e) {
		post("strudel: tempo read failed - " + e.message + "\n");
	}
}

function loadWebview() {
	try {
		var url = resolveUiUrl();
		if (!url) return;
		outlet(0, "url", url);
		post("strudel: sent url " + url + "\n");
	} catch (e) {
		post("strudel: loadWebview error " + e.message + "\n");
	}
}

/**
 * Locate the UI html and return a file:// URL that Chromium (jweb) can read.
 *
 * The build appends the UI to this very script as a base64 payload
 * (UI_PAYLOAD_B64 / UI_PAYLOAD_BYTES, generated by build-amxd.mjs). Frozen
 * dependencies only exist in Max's virtual filesystem, which Chromium can't
 * read - but this script provably runs, so it extracts the payload to a real
 * file next to the .amxd and points jweb at that. Without a payload (repo /
 * dev layout) it falls back to the loose copy next to the patcher.
 */
var UI_NAME = "strudel-ui.html";

function resolveUiUrl() {
	var fp = this.patcher.filepath;
	var devFolder = fp && fp.length ? fp.replace(/\/[^\/]*$/, "") : null;
	if (!devFolder) {
		post("strudel: patcher not saved yet - UI path unknown\n");
		return null;
	}
	var target = devFolder + "/" + UI_NAME;
	if (typeof UI_PAYLOAD_B64 !== "undefined") {
		extractPayload(target, UI_PAYLOAD_B64, UI_PAYLOAD_BYTES);
	} else {
		post("strudel: no embedded payload (dev build) - using " + target + "\n");
	}
	// Cache-buster: the URL changes per build, so Chromium can never serve a
	// page cached from a previous build of the same file path.
	return encodeURI("file:///" + target) + "?v=" + encodeURIComponent(buildStamp());
}

function buildStamp() {
	return typeof BUILD_STAMP !== "undefined" ? BUILD_STAMP : "dev";
}

/**
 * Node engine bootstrap. The patcher has [node.script ... @autostart 0] and
 * [js] owns the start sequence. The installed layout ships the .cjs loose
 * next to the .amxd (guaranteed present when node.script instantiates and
 * resolves its script argument); the embedded payload below is a fallback
 * for a bare .amxd copied on its own. node.script only accepts the
 * subcommands documented on its reference page (start/stop/npm/status/...),
 * so the script file itself cannot be repointed at runtime: extraction must
 * land the file under the exact name the object was created with.
 */
var nodeStarted = false;
var nodeStartTask = new Task(startNodeScript, this);
var nodeProbeTask = new Task(probeNodeScript, this);

function extractNodeBundle() {
	if (MODE !== "sampler") return; // midi/audio: engine runs in a jweb Web Worker
	if (nodeStarted) return;
	if (typeof NODE_PAYLOAD_B64 !== "undefined") {
		var fp = this.patcher.filepath;
		var devFolder = fp && fp.length ? fp.replace(/\/[^\/]*$/, "") : null;
		if (devFolder) {
			extractPayload(devFolder + "/" + NODE_PAYLOAD_NAME, NODE_PAYLOAD_B64, NODE_PAYLOAD_BYTES);
		} else {
			post("strudel: node extract - patcher path unknown, cannot extract\n");
		}
	}
	nodeStartTask.schedule(300);
}

function startNodeScript() {
	if (nodeStarted) return;
	nodeStarted = true;
	outlet(1, "script", "start");
	post("strudel: node.script start requested\n");
	nodeProbeTask.schedule(2000);
}

/**
 * Status probe, 2s after start. node.script answers "script running" on its
 * right (dump) outlet, which the patcher wires to [print n4m]. If the console
 * shows NO n4m line after this post, the js -> node.script message path is
 * dead (object missing or patchline dropped); if it shows "running 0", node
 * received the message but the script did not start.
 */
function probeNodeScript() {
	outlet(1, "script", "running");
	post("strudel: node.script status probe sent (expect an 'n4m:' console line)\n");
}

/**
 * Write an embedded base64 payload to targetPath. Skipped only when BOTH the
 * size matches AND a sidecar stamp file records the same build - size alone
 * proved too weak (different builds can collide, leaving a stale file that
 * no longer matches the wrapper driving it).
 */
function extractPayload(targetPath, b64chunks, byteCount) {
	try {
		var existing = new File(targetPath);
		if (existing.isopen) {
			var sameSize = existing.eof === byteCount;
			existing.close();
			if (sameSize && readTextFile(targetPath + ".stamp") === buildStamp()) return;
		}
	} catch (e) {
		/* fall through to (re)write */
	}
	try {
		var out = new File(targetPath, "write");
		if (!out.isopen) out.open();
		if (!out.isopen) {
			post("strudel: cannot write " + targetPath + "\n");
			return;
		}
		out.eof = 0;
		// File.writebytes silently truncates large calls (observed 16384-byte
		// cap), so write in small slices.
		var SLICE = 4096;
		for (var i = 0; i < b64chunks.length; i++) {
			var bytes = b64decode(b64chunks[i]);
			for (var off = 0; off < bytes.length; off += SLICE) {
				out.writebytes(bytes.slice(off, off + SLICE));
			}
		}
		out.close();
		var check = new File(targetPath);
		var written = check.isopen ? check.eof : -1;
		if (check.isopen) check.close();
		if (written === byteCount) {
			post("strudel: extracted " + written + " bytes to " + targetPath + "\n");
			writeTextFile(targetPath + ".stamp", buildStamp());
		} else {
			post("strudel: extract SIZE MISMATCH - wrote " + written + ", expected " + byteCount + "\n");
		}
	} catch (e2) {
		post("strudel: extract failed - " + e2.message + "\n");
	}
}

function readTextFile(p) {
	try {
		var f = new File(p);
		if (!f.isopen) return null;
		var s = f.readstring(Math.min(f.eof, 256));
		f.close();
		return s;
	} catch (e) {
		return null;
	}
}

function writeTextFile(p, s) {
	try {
		var f = new File(p, "write");
		if (!f.isopen) f.open();
		if (!f.isopen) return;
		f.eof = 0;
		f.writestring(s);
		f.close();
	} catch (e) {
		/* non-fatal */
	}
}

var B64CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
var b64lookup = null;

/** Base64 → array of byte values (Max js has no atob). */
function b64decode(s) {
	if (!b64lookup) {
		b64lookup = {};
		for (var i = 0; i < B64CHARS.length; i++) b64lookup[B64CHARS.charAt(i)] = i;
	}
	var out = [];
	var buffer = 0;
	var bits = 0;
	for (var j = 0; j < s.length; j++) {
		var c = s.charAt(j);
		if (c === "=") break;
		buffer = (buffer << 6) | b64lookup[c];
		bits += 6;
		if (bits >= 8) {
			bits -= 8;
			out.push((buffer >> bits) & 0xff);
		}
	}
	return out;
}

// Live 12 global scale observers (sampler device only): forward to the UI
// (key-aware filtering) and to [node.script] via outlet 1.
var rootObs = null,
	scaleObs = null,
	liveRoot = 0,
	liveScale = "Major";
function setupScaleObservers() {
	if (MODE !== "sampler") return;
	if (rootObs && scaleObs) return; // already set up
	try {
		rootObs = new LiveAPI(onRoot, "live_set");
		rootObs.property = "root_note";
		scaleObs = new LiveAPI(onScale, "live_set");
		scaleObs.property = "scale_name";
		post("strudel: scale observers ready\n");
	} catch (e) {
		post("strudel: scale observers unavailable (pre-Live-12?) " + e.message + "\n");
	}
}
function onRoot(a) {
	if (a && a[0] == "root_note") {
		liveRoot = a[1];
		sendScale();
	}
}
function onScale(a) {
	if (a && a[0] == "scale_name") {
		liveScale = a.slice(1).join(" ");
		sendScale();
	}
}
function sendScale() {
	outlet(0, "scale", liveRoot, liveScale); // → jweb (UI filter)
	outlet(1, "scale", liveRoot, liveScale); // → node
}

/** Return the LiveAPI for this device's own track. */
function ownTrack() {
	return new LiveAPI("this_device canonical_parent");
}

/**
 * write_clip <lengthBeats> <n> <p s d v> ...
 * Creates a clip in the first empty slot on this device's track.
 */
function write_clip() {
	var a = arrayfromargs(arguments);
	if (a.length < 2) return;
	var lengthBeats = a[0];
	var n = a[1];

	var slot = firstEmptySlot();
	if (!slot) {
		post("strudel: no empty clip slot on this track\n");
		return;
	}
	slot.call("create_clip", lengthBeats);
	var clip = new LiveAPI(slot.unquotedpath + " clip");

	var notes = [];
	for (var k = 0; k < n; k++) {
		var o = 2 + k * 4;
		notes.push({
			pitch: a[o],
			start_time: a[o + 1],
			duration: a[o + 2],
			velocity: a[o + 3],
			mute: 0,
		});
	}
	if (!addNotes(clip, notes)) {
		post("strudel: failed to add notes\n");
		return;
	}
	clip.set("name", "Strudel");
	post("strudel: wrote " + n + " notes over " + lengthBeats + " beats\n");
}

function firstEmptySlot() {
	try {
		var track = ownTrack();
		// Prefer the slot at the selected scene if it is empty.
		var count = parseInt(track.getcount("clip_slots"));
		for (var i = 0; i < count; i++) {
			var s = new LiveAPI(track.unquotedpath + " clip_slots " + i);
			if (parseInt(s.get("has_clip")) === 0) return s;
		}
		return null;
	} catch (e) {
		post("strudel: firstEmptySlot error " + e.message + "\n");
		return null;
	}
}

function addNotes(clip, notes) {
	try {
		clip.call("add_new_notes", { notes: notes });
		return true;
	} catch (e) {
		post("strudel: add_new_notes failed, trying legacy - " + e.message + "\n");
	}
	try {
		clip.call("set_notes");
		clip.call("notes", notes.length);
		for (var i = 0; i < notes.length; i++) {
			var nt = notes[i];
			clip.call("note", nt.pitch, nt.start_time, nt.duration, nt.velocity, nt.mute);
		}
		clip.call("done");
		return true;
	} catch (e2) {
		post("strudel: legacy set_notes failed - " + e2.message + "\n");
		return false;
	}
}

/**
 * read_notes - pick a clip on this device's track (playing clip → clip at the
 * selected scene → first clip found), read its notes, and send them to the UI.
 */
function read_notes() {
	var clip = pickClip();
	if (!clip) {
		post("strudel: no clip found on this track\n");
		outlet(0, "read_error", "no_clip");
		return;
	}
	var loopEnd = parseFloat(clip.get("loop_end"));
	var parsed = getNotes(clip, loopEnd);
	if (!parsed) return;

	var out = ["notes", loopEnd, parsed.length];
	for (var i = 0; i < parsed.length; i++) {
		out.push(parsed[i].pitch, parsed[i].start_time, parsed[i].duration);
	}
	outlet.apply(this, [0].concat(out));
	post("strudel: read " + parsed.length + " notes (loop_end " + loopEnd + ")\n");
}

function pickClip() {
	try {
		var track = ownTrack();
		var count = parseInt(track.getcount("clip_slots"));
		var firstWithClip = null;
		for (var i = 0; i < count; i++) {
			var s = new LiveAPI(track.unquotedpath + " clip_slots " + i);
			if (parseInt(s.get("has_clip")) === 1) {
				var c = new LiveAPI(s.unquotedpath + " clip");
				if (parseInt(c.get("is_playing")) === 1) return c;
				if (!firstWithClip) firstWithClip = c;
			}
		}
		return firstWithClip;
	} catch (e) {
		post("strudel: pickClip error " + e.message + "\n");
		return null;
	}
}

function getNotes(clip, loopEnd) {
	// Live 11+: get_notes_extended returns a JSON string.
	try {
		var d = clip.call("get_notes_extended", 0, 128, 0, loopEnd);
		var obj = typeof d === "string" ? JSON.parse(d) : d;
		if (obj && obj.notes) return obj.notes;
	} catch (e) {
		post("strudel: get_notes_extended failed, trying legacy - " + e.message + "\n");
	}
	// Legacy get_notes path
	try {
		clip.call("select_all_notes");
		var raw = clip.call("get_notes"); // returns list: notes n then note tuples
		return parseLegacyNotes(raw);
	} catch (e2) {
		post("strudel: legacy get_notes failed - " + e2.message + "\n");
		return null;
	}
}

function parseLegacyNotes(raw) {
	// raw = ["notes", count, "note", pitch, start, dur, vel, muted, ...]
	var notes = [];
	var i = 0;
	while (i < raw.length) {
		if (raw[i] === "note") {
			notes.push({
				pitch: raw[i + 1],
				start_time: raw[i + 2],
				duration: raw[i + 3],
				velocity: raw[i + 4],
			});
			i += 6;
		} else {
			i++;
		}
	}
	return notes;
}
